M48
; DRILL file {KiCad (6.0.9)} date Fr 23 Dez 2022 14:19:23 CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-12-23T14:19:23+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.580
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.660
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.152
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.200
%
G90
G05
T2
X77.3Y-75.44
T3
X72.0Y-43.6
X90.1Y-81.1
T4
X75.593Y-62.15
T1
G00X84.59Y-75.44
M15
G01X85.01Y-75.44
M16
G05
T0
M30
